config-version: 2
name: 'servicenow'
version: '0.7.0'

require-dbt-version: [">=1.3.0", "<3.0.0"]

models:
  servicenow:
    +schema: servicenow
    +materialized: table
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: view
      +schema: stg_servicenow

vars:
    task: "{{ source('servicenow','task') }}"
    task_sla: "{{ source('servicenow','task_sla') }}"
    sys_user: "{{ source('servicenow','sys_user') }}"
    problem: "{{ source('servicenow','problem') }}"
    problem_task: "{{ source('servicenow','problem_task') }}"
    incident: "{{ source('servicenow','incident') }}"
    change_task: "{{ source('servicenow','change_task') }}"
    change_request: "{{ source('servicenow','change_request') }}"
    core_company: "{{ source('servicenow','core_company') }}"
    cmdb_ci: "{{ source('servicenow','cmdb_ci') }}"
    cmdb_ci_service: "{{ source('servicenow','cmdb_ci_service') }}"
    sys_choice: "{{ source('servicenow','sys_choice') }}"
    sys_user_group: "{{ source('servicenow','sys_user_group') }}"
    sys_user_role: "{{ source('servicenow','sys_user_role') }}"
    sys_user_has_role: "{{ source('servicenow','sys_user_has_role') }}"
    sys_user_grmember: "{{ source('servicenow','sys_user_grmember') }}"

