name: 'servicenow_integration_tests'
version: '0.3.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  servicenow:
    servicenow_schema: servicenow_integration_tests_13
    servicenow_task_identifier: "task_data"
    servicenow_task_sla_identifier: "task_sla_data"
    servicenow_sys_user_identifier: "sys_user_data"
    servicenow_problem_identifier: "problem_data"
    servicenow_problem_task_identifier: "problem_task_data"
    servicenow_incident_identifier: "incident_data"
    servicenow_change_task_identifier: "change_task_data"
    servicenow_change_request_identifier: "change_request_data"
    servicenow_core_company_identifier: "core_company_data"
    servicenow_cmdb_ci_identifier: "cmdb_ci_data"
    servicenow_cmdb_ci_service_identifier: "cmdb_ci_service_data"
    servicenow_sys_user_group_identifier: "sys_user_group_data"
    servicenow_sys_user_role_identifier: "sys_user_role_data"
    servicenow_sys_user_has_role_identifier: "sys_user_has_role_data"
    servicenow_sys_user_grmember_identifier: "sys_user_grmember_data"

    # servicenow__using_roles: true # to be turned on when generating docs so that can be generated via the manifest and docs as it is turned off by default.

models:
  +schema: "servicenow_{{ var('directed_schema','dev') }}"

seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
  servicenow_integration_tests:
    +column_types:
      confirmed_at: "timestamp"
      fix_communicated_at: "timestamp"
      due_date: "timestamp"
      reopened_at: "timestamp"
      fix_at: "timestamp"
      resolved_at: "timestamp"
      workaround_communicated_at: "timestamp"
      group_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      role_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      user_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      name: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      includes_roles: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      roles: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      sys_id: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      sys_created_on: "timestamp"
      resolved_at: "timestamp"
      closed_at: "timestamp"
      market_cap: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      fix_at: "timestamp"
      requested_by_date: "timestamp"
      review_date: "timestamp"
      confirmed_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      first_reported_by_task_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      requested_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      fix_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      started_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      requested_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      problem_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      resolved_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      change_request_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      requested_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      assigned_to_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      closed_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      opened_by_value: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      sys_created_by: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
      sys_updated_by: "{{ 'varchar' if target.type in ['redshift', 'postgres', 'snowflake'] else 'string' }}"
    task_data:
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
    task_data_snowflake:
      +alias: task_data
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
